version: "3.0"
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network
  db:
    build: ./couchbase/
    deploy:
      replicas: 1
    environment:
      COUCHBASE_HOST: db
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    expose: # expose ports 8091 & 8094 to other containers (mainly for backend)
      - "8091"
      - "8094"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge